# Generated by Django 3.2.9 on 2022-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220118_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.ImageField(blank=True, null=True, upload_to='media/doctor'),
        ),
    ]
