# Generated by Django 3.2.9 on 2022-01-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220118_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.ImageField(blank=True, null=True, upload_to='doctor'),
        ),
    ]
