# Generated by Django 3.2.9 on 2022-01-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField()),
                ('per_time', models.IntegerField()),
                ('choice', models.CharField(choices=[('other', 'Other'), ('Post meal', 'Post meal'), ('Breakfast', 'Breakfast')], default='others', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
