# Generated by Django 3.2.9 on 2022-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_medications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medications',
            old_name='amount',
            new_name='dosage',
        ),
        migrations.RenameField(
            model_name='medications',
            old_name='per_time',
            new_name='times',
        ),
        migrations.AddField(
            model_name='medications',
            name='type',
            field=models.CharField(choices=[('other', 'Other'), ('Post meal', 'Post meal')], default='others', max_length=10),
        ),
        migrations.AlterField(
            model_name='medications',
            name='choice',
            field=models.CharField(choices=[('other', 'Other'), ('Breakfast', 'Breakfast')], default='others', max_length=10),
        ),
    ]
