# Generated by Django 3.2.9 on 2022-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220120_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiverDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='senderDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
