# Generated by Django 3.2.9 on 2022-01-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20220107_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_parent', to='pages.messages'),
        ),
    ]
