# Generated by Django 3.2.9 on 2022-01-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_messages_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
