# Generated by Django 3.2.9 on 2022-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='others', max_length=10),
        ),
    ]
